### ISSUE TITLE
Cloud Architecture Center shows twice in list

### ISSUE THREAD

**Issue by APratham** [sathishvj/awesome-gcp-certifications#32]
[Google Cloud Architecture Center<sup>BETA</sup>](https://cloud.google.com/architecture) is there two times in the list. One is as "Architecture Center" and another as "Cloud Solutions Architecture Reference". Kindly remove one of them to avoid confusion.

**Comment by sathishvj** [comment]
On which page is this showing twice?

**Comment by APratham** [comment]
It is on the main [README.md](https://github.com/sathishvj/awesome-gcp-certifications#common-resources) of the repo. I have highlighted both entries

![Screenshot 2021-05-17 222742](https://user-images.githubusercontent.com/33273990/118528067-8a992300-b75f-11eb-994f-884d1433477c.png)

**Comment by sathishvj** [comment]
Ok, got it.  
Looks like they have redirected the old gcp.solutions to the new architecture center.

I'll remove the old one.
