### ISSUE TITLE
Please update Professional Cloud Architect Google Cloud Certification Guide link

### ISSUE THREAD

**Issue by pietrask** [sathishvj/awesome-gcp-certifications#48]
There is a second edition released in Dec 2021

https://learning.oreilly.com/library/view/professional-cloud-architect/9781801812290/

**Comment by sathishvj** [comment]
Would you like to send in a pull request with that fix?  That way your contribution will show in the git history and in the contributors list.  If that's a bother, let me know, and i shall update it.

**Comment by pietrask** [comment]
Satish, I have created PR - https://github.com/sathishvj/awesome-gcp-certifications/pull/49

**Comment by sathishvj** [comment]
Pull request merged.
