### ISSUE TITLE
Broken link.

### ISSUE THREAD

**Issue by AshishBhadouria** [sathishvj/awesome-gcp-certifications#6]
| 2019/03 | [GCP Certified : The GCP Professional Cloud Security Engineer Exam (BETA)](https://antonitzavelas.com/2019/03/08/gcp-certified-the-gcp-professional-cloud-security-engineer-exam-beta/) | Antoni Tzavelas |

Link is broken.

**Comment by AshishBhadouria** [comment]
broken link.

**Comment by sathishvj** [comment]
updated.
